# Generated by Django 5.1 on 2024-08-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
